name: Acceptance tests
on:
    push:
        branches-ignore:
            - 'master'

concurrency:
    group: acceptance-tests-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Acceptance tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v3

            -   name: Create ngnix proxy network
                run: docker network create nginx-proxy

            -   name: Start containers and Acceptance test
                run: |
                    docker compose -f docker-compose.yml -f docker-compose.ci.all.yml up -d rabbitmq php-fpm nginx
                    docker compose -f docker-compose.yml -f docker-compose.ci.all.yml up composer
                    docker compose exec -T php-fpm bin/console
                    docker compose exec -T php-fpm chmod a+rwx log temp www tests -R
                    echo $(sh ./tests/migrations/migrate_structure.sh)
                    echo $(sh ./tests/migrations/migrate_data.sh)
                    docker compose exec -T php-fpm bash -c "cd tests/ && ../vendor/bin/codecept run"
