name: Production preview

on:
  push:
    branches:
      - master

jobs:
  build-image:
    uses: sheepstudio/xs-backend/.github/workflows/build-image.yml@master
    name: Build image
    with:
      image_tag: xs-backend:${GITHUB_SHA::8}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  deploy-production-preview:
    uses: ./.github/workflows/update-app-template.yml
    name: Deploy production preview to cluster
    needs: [ build-image ]
    with:
      namespace: staging-cz
      release_name: staging
      values_file: helm-charts/api/values-staging.yaml
      revision: ${GITHUB_SHA::8}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
