name: Phpstan
on:
    push:
        branches-ignore:
            - 'master'

concurrency:
    group: phpstan-tests-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Phpstan
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v3

            -   name: Create ngnix proxy network
                run: docker network create nginx-proxy

            -   name: Start containers and phpstan
                run: |
                    docker compose -f docker-compose.yml -f docker-compose.ci.yml up composer
                    docker compose run -T php-fpm vendor/bin/phpstan analyse -l max -c tests/phpstan.neon app --memory-limit 1G
