name: Release

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/update-app-template.yml
    name: Release api to production
    with:
      namespace: production-cz
      release_name: production
      values_file: helm-charts/api/values-production.yaml
      revision: ${GITHUB_SHA::8}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  manual-command:
    uses: ./.github/workflows/update-app-template.yml
    name: Release evn for manual commands
    with:
      namespace: production-cz
      release_name: manual-command
      values_file: helm-charts/api/values-production-manual-command.yaml
      revision: ${GITHUB_SHA::8}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
