name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Get date version
        id: version
        run: echo "::set-output name=version::$(date +'%y-%m-%d_%H-%M')"

      - name: Draft release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: true
          name: Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
